### ISSUE TITLE
Auto Reboots

### ISSUE THREAD

**Issue by Afsar-Pasha** [DrAcHe981/NeoPowerMenu#24]
When I open power menu phone gets restarted.
NeoPowerMenu v1.5.6-7
ROM:AOKP Marshmallow based r81

Crash log
11-24 16:52:47.494 I/Xposed  (14544): [NeoPowerMenu] java.lang.NullPointerException: Attempt to read from null array

**Comment by DrAcHe981** [comment]
One line of crash log is too less to know what causes it, I'd need the complete one... (filtered by either the package name "de.NeonSoft.neopowermenu", or the tag "NPM")

**Comment by Afsar-Pasha** [comment]
[Xposed log.txt](https://github.com/DrAcHe981/NeoPowerMenu/files/1502989/Xposed.log.txt)
When I open power menu phone reboots so, here is the Xposed log from /data/data/de.robv.android.xposed.installer/log/**error.log.old**

**Comment by DrAcHe981** [comment]
No information about the crash/reboot in that xposed log, everything seems normal besides that the log says the preferences file isn't world readable
I also analyzed the AOKP rom files but found nothing obvious that could cause that crash/reboot

I need a normal logcat, if possible connect your device to a pc to create an adb logcat using the command "adb logcat *:E -v long > crash.txt", then do what causes the crash and give that log file to me

**Comment by Afsar-Pasha** [comment]
Switched to  another ROM, now it works fine.

**Comment by DrAcHe981** [comment]
Well... Not really a solution for me in terms of making compatibility, but I guess that works too

Case closed then until the next one with AOKP has troubles
